[features]
seeds = false
skip-lint = false
[programs.localnet]
mycalculatorapp = "2LDHYi9vota824dwa2R3Jq125f8r2jfMLHkRUgZbUgvR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/danil_sitdikov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
